default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: okaki_development

test:
  <<: *default
  database: okaki_test

production:
  <<: *default
  database: okaki
